goals:
  goal_1:
    - position:
        x: 1.5
        y: 3.5
      orientation:
        Z: 0.0
        W: 1.0
  goal_2:
    - position:
        x: 5.7
        y: 3.5
      orientation:
        Z: 0.0
        W: 1.0
  goal_3:
    - position:
        x: 5.7
        y: 0.15
      orientation:
        Z: 1.0
        W: 0.0
  goal_4:
    - position:
        x: 4.0
        y: 0.15
      orientation:
        Z: 1.0
        W: 0.0
